name: 'Titan Core: Snowflake infrastructure as code'
author: Titan Systems, Inc
description: 'Deploy to Snowflake with Titan'
inputs:
  run-mode:
    description: 'Run mode determines which actions can be performed. `create-or-update` mode will never drop, rename, or change ownership of resources.'
    required: true
    default: 'create-or-update'
  resource-path:
    description: 'Resource path should point to the file or folder in the repo that contains the resource configuration.'
    required: true
    default: '.'
  allowlist:
    description: 'Allowlist is a comma-separated list of resource types that Titan is allowed to manage. If not provided, Titan will manage all resources.'
    required: false
    default: 'all'
  dry-run:
    description: 'When dry run is true, Titan will not make any changes to Snowflake.'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'terminal'
  color: 'orange'
